services:
  mottu-api:
    build:
      context: .
      dockerfile: src/Mottu.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=mottu_db;Username=mottu_user;Password=mottu_password
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    depends_on:
      - postgres-db
      - rabbitmq

  postgres-db:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=mottu_db
      - POSTGRES_USER=mottu_user
      - POSTGRES_PASSWORD=mottu_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  postgres_data:
